// ============ ÇEVİRİLER (TRANSLATIONS) ============
const translations = {
    tr: {
        heroTitle: "Her Araçın Geçmişini Saniyeler İçinde Öğren",
        heroDesc: "İthalatçı araçlar için güvenilir hizmet. Araçların geçmişini, kaza durumunu, yüksek kilometre ve sorunları satın almadan öğrenin.",
        placeholder: "VIN numarasını girin (17 karakter)",
        submitBtn: "KONTROL ET",
        loadingText: "Kontrol ediliyor...",
        errorText: "17 karakterli geçerli bir VIN girin",
        featuresTitle: "Ne Bulacaksınız?",
        feature1: "Kaza Geçmişi ve Hasarlar",
        feature2: "Teknik Özellikler ve Donanım",
        feature3: "Kilometre Bilgisi",
        feature4: "Kayıt Geçmişi",
        feature5: "Servis ve Onarım Geçmişi",
        feature6: "Araç Fotoğrafları",
        howTitle: "VIN Kodu Nasıl Kontrol Edilir?",
        step1Title: "VIN Numarasını Girin",
        step1Desc: "Araç penceresindeki 17 karakterli VIN numarasını arama kutusuna girin ve KONTROL ET butonuna tıklayın.",
        step2Title: "Tam Rapor Satın Alın",
        step2Desc: "Kazalar, eski sahipleri, hasarlar, teknik durum ve tüm detaylı bilgileri içeren tam raporu edinin.",
        step3Title: "Araç Geçmişini İnceleyiniz",
        step3Desc: "Tam rapor ile satın almadan önce tüm riskleri görmek ve doğru kararlar vermek için gereken bilgilere sahip olun.",
        whatTitle: "DeepCar.vin Raporunda Ne Var?",
        get1: "Kayıt ve Sahip Geçmişi",
        get2: "Kaza Geçmişi ve Hasarlar",
        get3: "Yasal Statüsü",
        get4: "Kilometre Bilgisi",
        get5: "Servis ve Onarım Kayıtları",
        get6: "Teknik Özellikler",
        get7: "Sorunlar ve Arızalar",
        get8: "Araç Fotoğrafları",
        copyright: "© 2024 DeepCar.vin",
        email: "support@deepcar.vin",
        link1: "Hakkında",
        link2: "İletişim",
        link3: "Gizlilik",
        link4: "Şartlar"
    },
    ru: {
        heroTitle: "Узнайте историю автомобиля за считанные секунды",
        heroDesc: "Надежный сервис для проверки импортных автомобилей. Узнайте историю, аварии, пробег и проблемы до покупки.",
        placeholder: "Введите VIN (17 символов)",
        submitBtn: "ПРОВЕРИТЬ",
        loadingText: "Проверка...",
        errorText: "Введите корректный VIN (17 символов)",
        featuresTitle: "Что вы найдете?",
        feature1: "История аварий и повреждений",
        feature2: "Технические характеристики",
        feature3: "Информация о пробеге",
        feature4: "История регистрации",
        feature5: "История обслуживания",
        feature6: "Фотографии автомобиля",
        howTitle: "Как проверить VIN код?",
        step1Title: "Введите VIN номер",
        step1Desc: "Введите 17-значный VIN номер в поле поиска и нажмите кнопку ПРОВЕРИТЬ.",
        step2Title: "Получите полный отчет",
        step2Desc: "Получите информацию об авариях, предыдущих владельцах, повреждениях и всех важных деталях.",
        step3Title: "Изучите историю автомобиля",
        step3Desc: "Используя полный отчет, вы сможете увидеть все риски и принять правильное решение перед покупкой.",
        whatTitle: "Что входит в отчет DeepCar.vin?",
        get1: "История регистрации и владельцев",
        get2: "История аварий и повреждений",
        get3: "Юридический статус",
        get4: "Информация о пробеге",
        get5: "Записи об обслуживании",
        get6: "Технические характеристики",
        get7: "Проблемы и неисправности",
        get8: "Фотографии автомобиля",
        copyright: "© 2024 DeepCar.vin",
        email: "support@deepcar.vin",
        link1: "О нас",
        link2: "Контакты",
        link3: "Конфиденциальность",
        link4: "Условия"
    },
    ky: {
        heroTitle: "Ар бир унаанын историясын секундада билиңиз",
        heroDesc: "Импорттолгон унаалар үчүн ишенимдүү кызмат. Историясын, авариялык окуяларын, км-син жана ар түрдүү көйгөйлөрүн сатып алуудан мурун билиңиз.",
        placeholder: "VIN номерин киргизиңиз (17 символ)",
        submitBtn: "ТЕКШЕРҮҮ",
        loadingText: "Текшерилүүдө...",
        errorText: "Туура VIN номерин киргизиңиз (17 символ)",
        featuresTitle: "Эмне табасыз?",
        feature1: "Авария жана зыян тарыхы
